const all=window.APPROVALS, research=window.RESEARCH;let page=1;const per=50;
const $=s=>document.querySelector(s);const money=n=>new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(n);
const provinces=[...new Set(all.map(x=>x.province))].sort();provinces.forEach(p=>$('#province').insertAdjacentHTML('beforeend',`<option>${p}</option>`));
$('#stats').innerHTML=`<div class="stat"><b>${all.length.toLocaleString()}</b><span>approval records</span></div><div class="stat"><b>${money(all.reduce((a,b)=>a+b.amount,0))}</b><span>total published package value</span></div><div class="stat"><b>${provinces.length}</b><span>provinces represented</span></div><div class="stat"><b>${all.filter(x=>x.research_status==='Researched').length}</b><span>profiles researched so far</span></div>`;
function filtered(){let q=$('#q').value.trim().toLowerCase(),p=$('#province').value,s=$('#status').value;let a=all.filter(x=>(!q||[x.beneficiary,x.province,x.district,x.municipality].join(' ').toLowerCase().includes(q))&&(!p||x.province===p)&&(!s||x.research_status===s));let sort=$('#sort').value;if(sort==='amount-desc')a.sort((x,y)=>y.amount-x.amount||x.id-y.id);if(sort==='date-desc')a.sort((x,y)=>y.approval_date_iso.localeCompare(x.approval_date_iso));if(sort==='name')a.sort((x,y)=>x.beneficiary.localeCompare(y.beneficiary));if(sort==='id')a.sort((x,y)=>x.id-y.id);return a}
function render(){let a=filtered(),pages=Math.max(1,Math.ceil(a.length/per));if(page>pages)page=pages;let slice=a.slice((page-1)*per,page*per);$('#resultCount').textContent=`${a.length.toLocaleString()} records`;$('#tbody').innerHTML=slice.map(x=>`<tr><td>${x.id}</td><td><button class="namebtn" data-id="${x.id}">${esc(x.beneficiary)}</button></td><td>${x.approval_date}</td><td>${x.province}</td><td>${esc(x.district)}</td><td>${esc(x.municipality)}</td><td class="amount">${money(x.amount)}</td><td><span class="badge ${x.research_status==='Researched'?'good':''}">${esc(x.verification)}</span></td></tr>`).join('');$('#pageLabel').textContent=`Page ${page} of ${pages}`;$('#prev').disabled=page<=1;$('#next').disabled=page>=pages;document.querySelectorAll('.namebtn').forEach(b=>b.onclick=()=>openProfile(+b.dataset.id))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function openProfile(id){let x=all.find(r=>r.id===id),r=research[x.beneficiary];let body=`<div class="eyebrow" style="color:#65736d">APPROVAL #${x.id}</div><h2>${esc(x.beneficiary)}</h2><div class="profile-grid"><div class="kv"><small>Approval date</small>${x.approval_date}</div><div class="kv"><small>Package</small>${money(x.amount)}</div><div class="kv"><small>Province</small>${esc(x.province)}</div><div class="kv"><small>District</small>${esc(x.district)}</div><div class="kv"><small>Municipality</small>${esc(x.municipality)}</div><div class="kv"><small>Source page</small>Page ${x.source_page} of Annexure A</div></div>`;if(r){body+=`<div class="research"><span class="badge good">${esc(r.verification)}</span><h3>Independent public-record research</h3><p>${esc(r.summary)}</p><table><tbody>${r.facts.map(f=>`<tr><th>${esc(f[0])}</th><td>${esc(f[1])}</td></tr>`).join('')}</tbody></table><div class="sources"><strong>Sources:</strong><br>${r.sources.map(s=>`<a href="${s.url}" target="_blank" rel="noopener">${esc(s.label)} ↗</a>`).join('')}</div><div class="caution"><strong>Identity caution:</strong> ${esc(r.caution)}</div></div>`}else{body+=`<div class="research"><h3>Research not started</h3><p>This profile currently contains only the information published in Annexure A. No inference should be made from the absence of public research.</p></div>`}$('#modalBody').innerHTML=body;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false')}
['q','province','status','sort'].forEach(id=>$('#'+id).addEventListener(id==='q'?'input':'change',()=>{page=1;render()}));$('#prev').onclick=()=>{page--;render();scrollTo({top:350,behavior:'smooth'})};$('#next').onclick=()=>{page++;render();scrollTo({top:350,behavior:'smooth'})};$('#close').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').classList.remove('open')};
$('#downloadBtn').onclick=()=>{let a=filtered(),cols=['id','beneficiary','approval_date','province','district','municipality','amount','research_status','verification'];let csv=[cols.join(','),...a.map(x=>cols.map(k=>'"'+String(x[k]??'').replaceAll('"','""')+'"').join(','))].join('\n');let blob=new Blob([csv],{type:'text/csv'}),u=URL.createObjectURL(blob),link=document.createElement('a');link.href=u;link.download='spaza-approvals-filtered.csv';link.click();URL.revokeObjectURL(u)};render();